// Builds the browser-ready classic script so index.html works via file://.
// Source files remain small ES modules for maintenance; the generated file is
// checked into the project and needs no build command when opening the site.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const shared = ['data', 'categories', 'location', 'common'];
const pages = ['catalog', 'create-listing', 'listing', 'favorites', 'messages', 'profile'];

function compile(source, name, isPage) {
  const exports = [];
  let result = source.replace(/^import\s*\{([\s\S]*?)\}\s*from\s*['"]\.\/([\w-]+)\.js['"];\s*/gm, (_, bindings, dependency) => {
    const named = bindings.trim().split(',').map((item) => {
      const [original, alias] = item.trim().split(/\s+as\s+/);
      return alias ? `${original.trim()}: ${alias.trim()}` : original.trim();
    }).join(', ');
    return `const { ${named} } = __market.${dependency.replaceAll('-', '_')};\n`;
  });
  result = result.replace(/^export\s+(const|let|var|function|class)\s+([\w$]+)/gm, (_, kind, exported) => {
    exports.push(exported);
    return `${kind} ${exported}`;
  });
  if (/^\s*(?:import|export)\s/m.test(result)) throw new Error(`Unsupported module syntax in ${name}.js`);
  const body = `'use strict';\n${result}\n`;
  return isPage
    ? `function __run_${name.replaceAll('-', '_')}() {\n${body}}\n`
    : `__market.${name.replaceAll('-', '_')} = (() => {\n${body}return { ${exports.join(', ')} };\n})();\n`;
}

let output = '// Generated by tools/build-static.mjs. Open index.html directly; no server is required.\n(() => {\nconst __market = Object.create(null);\n';
for (const name of shared) output += compile(await readFile(resolve(root, 'js', `${name}.js`), 'utf8'), name, false);
for (const name of pages) output += compile(await readFile(resolve(root, 'js', `${name}.js`), 'utf8'), name, true);
output += `const file = location.pathname.split('/').pop().toLowerCase() || 'index.html';\n`;
output += `const run = ({ 'index.html': __run_catalog, 'create.html': __run_create_listing, 'listing.html': __run_listing, 'favorites.html': __run_favorites, 'messages.html': __run_messages, 'profile.html': __run_profile })[file];\n`;
output += `if (run) run();\n})();\n`;
await writeFile(resolve(root, 'js', 'app.bundle.js'), output, 'utf8');
console.log('Built js/app.bundle.js');
